name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api-gateway/**'
      - '.github/workflows/api-gateway.yml'

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd api-gateway && yarn install 
      - run: cd api-gateway && yarn build
