name: Api Gateway Dockerize

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'api-gateway/**'
      - '.github/workflows/api-gateway-*.yml'

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Create ECR repository if not exists
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: api-gateway
        run: |
          aws ecr describe-repositories --repository-names "$ECR_REPOSITORY" \
            || aws ecr create-repository --repository-name "$ECR_REPOSITORY" --region "$AWS_REGION"

      - name: Build and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: api-gateway
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./api-gateway
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
